"""Rebuild checked-in Windows x64 launchers with MSVC and official CPython headers.

Run from an x64 Native Tools prompt, or pass --vcvars to vcvars64.bat.
Downloads and intermediate files stay below --build-dir (default: build/launcher).
No installed Python development libraries or third-party compiler are required.
"""

from __future__ import annotations

import argparse
import base64
from concurrent.futures import ThreadPoolExecutor
import hashlib
import os
from pathlib import Path
import shutil
import subprocess
import tarfile
import urllib.request
import zlib


ROOT = Path(__file__).resolve().parents[1]
# PyConfig's public structure layout varies by minor, not patch, release.
VERSIONS = ("3.9.13", "3.10.11", "3.11.9", "3.12.10", "3.13.7")
ARCHIVE_SHA256 = {
    "3.9.13": "125b0c598f1e15d2aa65406e83f792df7d171cdf38c16803b149994316a3080f",
    "3.10.11": "3c3bc3048303721c904a03eb8326b631e921f11cc3be2988456a42f115daf04c",
    "3.11.9": "9b1e896523fc510691126c864406d9360a3d1e986acbda59cda57b5abda45b87",
    "3.12.10": "07ab697474595e06f06647417d3c7fa97ded07afc1a7e4454c5639919b46eaea",
    "3.13.7": "5462f9099dfd30e238def83c71d91897d8caa5ff6ebc7a50f14d4802cdaaa79a",
}


def source_digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes().replace(b"\r\n", b"\n")).hexdigest()


def prepare_headers(version: str, build_dir: Path) -> Path:
    archive = build_dir / f"Python-{version}.tar.xz"
    if not archive.exists():
        url = f"https://www.python.org/ftp/python/{version}/Python-{version}.tar.xz"
        print(f"Downloading {url}", flush=True)
        urllib.request.urlretrieve(url, archive)
    if hashlib.sha256(archive.read_bytes()).hexdigest() != ARCHIVE_SHA256[version]:
        raise ValueError(f"CPython source archive SHA256 mismatch: {archive}")
    headers = build_dir / f"headers-{version}"
    headers.mkdir(exist_ok=True)
    prefix = f"Python-{version}/"
    with tarfile.open(archive) as source:
        for member in source:
            if not member.isfile() or not member.name.startswith(prefix):
                continue
            name = member.name[len(prefix):]
            if name.startswith("Include/") and name.endswith(".h"):
                relative = Path(name[len("Include/"):])
            elif name in {"PC/pyconfig.h", "PC/pyconfig.h.in"}:
                relative = Path("pyconfig.h")
            else:
                continue
            target = (headers / relative).resolve()
            target.relative_to(headers.resolve())
            target.parent.mkdir(parents=True, exist_ok=True)
            stream = source.extractfile(member)
            assert stream is not None
            target.write_bytes(stream.read())
    return headers


def compiler_environment(vcvars: Path | None) -> dict[str, str]:
    if vcvars is None and shutil.which("cl.exe"):
        return dict(os.environ)
    if vcvars is None:
        installation = Path(os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)"))
        vcvars = installation / "Microsoft Visual Studio/2022/BuildTools/VC/Auxiliary/Build/vcvars64.bat"
    if not vcvars.is_file():
        raise SystemExit("Use an x64 Native Tools prompt or provide --vcvars PATH.")
    # cmd is required to import this vendor-supplied batch environment. No file
    # mutation or task-provided shell commands are passed to this helper.
    if '"' in str(vcvars):
        raise ValueError("Invalid compiler environment path")
    completed = subprocess.run(
        f'cmd.exe /d /s /c ""{vcvars}" >nul && set"',
        check=True, stdout=subprocess.PIPE, text=True,
    )
    return dict(line.split("=", 1) for line in completed.stdout.splitlines() if "=" in line and not line.startswith("="))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--build-dir", type=Path, default=ROOT / "build/launcher")
    parser.add_argument("--output", type=Path, default=ROOT / "src/coil/_launcher_stubs.py")
    parser.add_argument("--vcvars", type=Path)
    args = parser.parse_args()
    build_dir = args.build_dir.resolve()
    build_dir.mkdir(parents=True, exist_ok=True)
    source = ROOT / "src/coil/templates/launcher.c"
    environment = compiler_environment(args.vcvars)
    compiler = shutil.which("cl.exe", path=next(value for key, value in environment.items() if key.lower() == "path"))
    if not compiler:
        raise SystemExit("MSVC cl.exe was not found in the compiler environment")
    with ThreadPoolExecutor(max_workers=len(VERSIONS)) as executor:
        headers = dict(zip(VERSIONS, executor.map(lambda version: prepare_headers(version, build_dir), VERSIONS)))
    lines = [
        '"""Generated by tools/build_launcher.py; do not edit encoded stubs by hand."""',
        "", "import base64", "import zlib", "",
        f'SOURCE_SHA256 = "{source_digest(source)}"',
        f'MANIFEST_SHA256 = "{source_digest(source.with_suffix(".manifest"))}"',
        "STUBS: dict[str, bytes] = {}", "",
        "", "def _delta(encoded: bytes) -> bytes:",
        '    """Restore minor-version changes against the shared 3.9 PE image."""',
        "    delta = zlib.decompress(base64.b64decode(encoded))",
        '    base = STUBS["3.9"]',
        "    if len(delta) != len(base):",
        '        raise RuntimeError("Corrupt native launcher delta")',
        "    return bytes(left ^ right for left, right in zip(base, delta))", "",
    ]
    base_blob = None
    for version in VERSIONS:
        minor = ".".join(version.split(".")[:2])
        exe = build_dir / f"launcher-{minor}.exe"
        obj = build_dir / f"launcher-{minor}.obj"
        command = [compiler, "/nologo", "/O1", "/MT", "/W4", "/std:c11", "/Brepro",
                   "/DUNICODE", "/D_UNICODE", f"/I{headers[version]}", str(source),
                   f"/Fo{obj}", f"/Fe{exe}", "/link", "/SUBSYSTEM:CONSOLE", "/MACHINE:X64",
                   "/DYNAMICBASE", "/NXCOMPAT", "/HIGHENTROPYVA", "/Brepro",
                   "/MANIFEST:EMBED", f"/MANIFESTINPUT:{source.with_suffix('.manifest')}"]
        subprocess.run(command, cwd=build_dir, env=environment, check=True)
        blob = exe.read_bytes()
        delta = base_blob is not None and len(base_blob) == len(blob)
        payload = bytes(left ^ right for left, right in zip(base_blob, blob)) if delta else blob
        encoded = base64.b64encode(zlib.compress(payload, 9)).decode("ascii")
        if base_blob is None:
            base_blob = blob
        lines.extend([f"# CPython {version}; {len(blob)} bytes; SHA256 {hashlib.sha256(blob).hexdigest()}",
                      f'STUBS["{minor}"] = ' + ("_delta(" if delta else "zlib.decompress(base64.b64decode(")])
        lines.extend(f'    b"{encoded[pos:pos + 100]}"' for pos in range(0, len(encoded), 100))
        lines.extend([")" if delta else "))", ""])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8", newline="\n") as output:
        output.write("\n".join(lines))
    print(f"Wrote {args.output}", flush=True)


if __name__ == "__main__":
    main()
